### PR TITLE
moved defer statements after error checking

### PR DESCRIPTION
**Pull request by briandowns**

### CODE REVIEW

**Comment by briandowns** [comment]
This is a cool little app.  Nice work.

**Comment by michaelhue** [comment]
Hey Brian! I just noticed your pull requests after spotting your fork five minutes ago and already implementing your changes. Sorry about that, I credited you in the commit message. Thanks for your improvements and I'm glad you like `rgif`. Check out the new version! :)

One question if you don't mind: I noticed you re-organized the import statements to local/remote groups. I run `go fmt` before every commit which sorts the imports alphabetically. Is this considers bad practice? Thanks again!

**Comment by briandowns** [comment]
Sounds good.  

As for the reorg of the imports, vim does that on save.  Apologies if this has caused a problem or confusion.  In regards to internal and external packages, I don't know if it's best practice or not to segment them however in terms of readability, it certainly has it's merits.  I've noticed that most packages has their imports structured in that way as well.

**Comment by michaelhue** [comment]
No problem at all, just curious. Thanks for the explanation!

**Pull request closed without merging**
